In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/cleaned/superstore_enriched.csv")

In [3]:
customers = df[
    [
        "Customer ID",
        "Customer Name",
        "Segment"
    ]
].drop_duplicates().reset_index(drop=True)

In [4]:
customers.columns = [
    "customer_id",
    "customer_name",
    "segment"
]

In [5]:
customers.head()

  customer_id    customer_name    segment
0    CG-12520      Claire Gute   Consumer
1    DV-13045  Darrin Van Huff  Corporate
2    SO-20335   Sean O'Donnell   Consumer
3    BH-11710  Brosina Hoffman   Consumer
4    AA-10480     Andrew Allen   Consumer

In [6]:
customers.shape

(793, 3)

In [7]:
customers.duplicated().sum()

np.int64(0)

In [8]:
customers.to_csv(
    "../data/normalized/customers.csv",
    index=False
)

print("customers.csv created successfully!")

customers.csv created successfully!

In [9]:
products = df[
    [
        "Product ID",
        "Product Name",
        "Category",
        "Sub-Category"
    ]
].drop_duplicates().reset_index(drop=True)

In [10]:
products.columns = [
    "product_id",
    "product_name",
    "category",
    "sub_category"
]

In [11]:
products.head()

,product_id,product_name,category,sub_category
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage

In [12]:
products.shape

(1894, 4)

In [13]:
products.duplicated().sum()

np.int64(0)

In [14]:
products.to_csv(
    "../data/normalized/products.csv",
    index=False
)

print("products.csv created successfully!")

products.csv created successfully!

In [15]:
locations = df[
    [
        "Country",
        "Region",
        "State",
        "City",
        "Postal Code"
    ]
].drop_duplicates().reset_index(drop=True)

In [16]:
locations.columns = [
    "country",
    "region",
    "state",
    "city",
    "postal_code"
]

In [17]:
locations.insert(
    0,
    "location_id",
    range(1, len(locations) + 1)
)

In [18]:
locations.head()

,location_id,country,region,state,city,postal_code
0,1,United States,South,Kentucky,Henderson,42420
1,2,United States,West,California,Los Angeles,90036
2,3,United States,South,Florida,Fort Lauderdale,33311
3,4,United States,West,California,Los Angeles,90032
4,5,United States,South,North Carolina,Concord,28027

In [19]:
locations.shape

(632, 6)

In [20]:
locations.to_csv(
    "../data/normalized/locations.csv",
    index=False
)

print("locations.csv created successfully!")

locations.csv created successfully!

In [21]:
orders = df.copy()

In [22]:
orders = orders[
    [
        "Order ID",
        "Order Date",
        "Ship Date",
        "Ship Mode",
        "Customer ID",
        "Product ID",
        "Country",
        "Region",
        "State",
        "City",
        "Postal Code",
        "Sales",
        "Quantity",
        "Discount",
        "Profit"
    ]
]

In [23]:
orders.columns = [
    "order_id",
    "order_date",
    "ship_date",
    "ship_mode",
    "customer_id",
    "product_id",
    "country",
    "region",
    "state",
    "city",
    "postal_code",
    "sales",
    "quantity",
    "discount",
    "profit"
]

In [24]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,country,region,state,city,postal_code,sales,quantity,discount,profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-BO-10001798,United States,South,Kentucky,Henderson,42420,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-CH-10000454,United States,South,Kentucky,Henderson,42420,731.9400,3,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,OFF-LA-10000240,United States,West,California,Los Angeles,90036,14.6200,2,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,FUR-TA-10000577,United States,South,Florida,Fort Lauderdale,33311,957.5775,5,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,OFF-ST-10000760,United States,South,Florida,Fort Lauderdale,33311,22.3680,2,0.20,2.5164

In [25]:
orders.shape

(9994, 15)

In [26]:
orders = orders.merge(
    locations,
    on=["country", "region", "state", "city", "postal_code"],
    how="left"
)

In [27]:
orders["location_id"].isnull().sum()

np.int64(0)

In [28]:
orders = orders[
    [
        "order_id",
        "order_date",
        "ship_date",
        "ship_mode",
        "customer_id",
        "product_id",
        "location_id",
        "sales",
        "quantity",
        "discount",
        "profit"
    ]
]

In [29]:
orders.head()

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,location_id,sales,quantity,discount,profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-BO-10001798,1,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-CH-10000454,1,731.9400,3,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,OFF-LA-10000240,2,14.6200,2,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,FUR-TA-10000577,3,957.5775,5,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,OFF-ST-10000760,3,22.3680,2,0.20,2.5164

In [30]:
orders.shape

(9994, 11)

In [31]:
orders.to_csv(
    "../data/normalized/orders.csv",
    index=False
)

print("orders.csv created successfully!")

orders.csv created successfully!

In [32]:
import os

os.listdir("../data/normalized")

['customers.csv', 'locations.csv', 'orders.csv', 'products.csv']

In [33]:
products["product_id"].duplicated().sum()

np.int64(32)

In [34]:
products.shape

(1894, 4)

In [35]:
products = products.drop_duplicates(subset=["product_id"])

In [36]:
products.shape

(1862, 4)

In [37]:
products["product_id"].duplicated().sum()

np.int64(0)

In [38]:
products.to_csv("../data/normalized/products.csv", index=False)

In [39]:
import pandas as pd

orders = pd.read_csv("../data/normalized/orders.csv")

print("Rows:", orders.shape[0])
print("Duplicate Order IDs:", orders["order_id"].duplicated().sum())

orders[orders["order_id"].duplicated(keep=False)].sort_values("order_id").head(20)

Rows: 9994
Duplicate Order IDs: 4985

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,location_id,sales,quantity,discount,profit
6288,CA-2014-100090,2014-07-08,2014-07-12,Standard Class,EB-13705,OFF-BI-10001597,35,196.704,6,0.2,68.8464
6287,CA-2014-100090,2014-07-08,2014-07-12,Standard Class,EB-13705,FUR-TA-10003715,35,502.488,3,0.2,-87.9354
3835,CA-2014-100363,2014-04-08,2014-04-15,Standard Class,JM-15655,OFF-FA-10000611,277,2.368,2,0.2,0.8288
3836,CA-2014-100363,2014-04-08,2014-04-15,Standard Class,JM-15655,OFF-PA-10004733,277,19.008,3,0.2,6.8904
6571,CA-2014-100678,2014-04-18,2014-04-22,Standard Class,KM-16720,TEC-AC-10000474,15,227.976,3,0.2,28.4970
6568,CA-2014-100678,2014-04-18,2014-04-22,Standard Class,KM-16720,OFF-AR-10001868,15,2.688,2,0.2,1.0080
6569,CA-2014-100678,2014-04-18,2014-04-22,Standard Class,KM-16720,FUR-CH-10002602,15,317.058,3,0.3,-18.1176
6570,CA-2014-100678,2014-04-18,2014-04-22,Standard Class,KM-16720,OFF-EN-10000056,15,149.352,3,0.2,50.4063
9019,CA-2014-100706,2014-12-16,2014-12-18,Second Class,LE-16810,TEC-AC-10001314,29,99.980,2,0.0,7.9984
9020,CA-2014-100706,2014-12-16,2014-12-18,Second Class,LE-16810,FUR-FU-10002268,29,29.460,6,0.0,9.7218
6317,CA-2014-100762,2014-11-24,2014-11-29,Standard Class,NG-18355,OFF-PA-10004082,31,15.960,2,0.0,7.9800
6314,CA-2014-100762,2014-11-24,2014-11-29,Standard Class,NG-18355,OFF-AR-10000380,31,151.920,4,0.0,45.5760
6315,CA-2014-100762,2014-11-24,2014-11-29,Standard Class,NG-18355,OFF-LA-10003930,31,196.620,2,0.0,96.3438
6316,CA-2014-100762,2014-11-24,2014-11-29,Standard Class,NG-18355,OFF-PA-10001815,31,144.120,3,0.0,69.1776
3888,CA-2014-100895,2014-06-02,2014-06-06,Standard Class,SV-20785,TEC-PH-10001425,237,239.970,3,0.0,67.1916
3887,CA-2014-100895,2014-06-02,2014-06-06,Standard Class,SV-20785,OFF-AR-10004511,237,8.560,2,0.0,2.6536
3889,CA-2014-100895,2014-06-02,2014-06-06,Standard Class,SV-20785,OFF-ST-10001490,237,356.940,2,0.0,107.0820
7572,CA-2014-100916,2014-10-21,2014-10-26,Standard Class,FH-14275,FUR-TA-10004607,390,591.320,4,0.0,112.3508
7571,CA-2014-100916,2014-10-21,2014-10-26,Standard Class,FH-14275,OFF-ST-10003479,390,194.700,5,0.0,9.7350
7573,CA-2014-100916,2014-10-21,2014-10-26,Standard Class,FH-14275,OFF-AR-10001022,390,2.840,1,0.0,0.8804